<?php

return [
    'name' => 'yoo_load_more',
    'title' => 'Dynamic Load More',
    'group' => 'YOO Load More',
    'icon' => '${url:images/icon.svg}',
    'iconSmall' => '${url:images/iconSmall.svg}',
    'element' => true,
    'width' => 500,
    'defaults' => [
        'mode' => 'button',
        'target_selector' => '.uk-grid',
        'item_selector' => ':scope > *',
        'pagination_selector' => '.uk-pagination',
        'next_selector' => 'a[rel="next"], a.next, .next.page-numbers, .uk-pagination-next a',
        'default_text' => 'Load more',
        'loading_text' => 'Loading…',
        'no_more_text' => 'No more posts',
        'button_style' => 'uk-button-default',
        'button_size' => '',
        'root_margin' => '300px 0px',
        'debounce' => 200,
        'hide_pagination' => true,
        'update_browser_url' => false,
    ],
    'templates' => [
        'render' => __DIR__ . '/templates/template.php',
        'content' => __DIR__ . '/templates/content.php',
    ],
    'fields' => [
        'mode' => [
            'label' => 'Trigger Mode',
            'type' => 'select',
            'options' => [
                'Button' => 'button',
                'Infinite Scroll' => 'infinite',
                'Hybrid (button, then infinite)' => 'hybrid',
            ],
        ],
        'target_selector' => [
            'label' => 'Target Grid Selector',
            'description' => 'CSS selector for the rendered grid. Use a unique class on the target Grid when the page contains more than one grid.',
        ],
        'item_selector' => [
            'label' => 'Grid Item Selector',
            'description' => 'Selector evaluated inside the target grid. The default selects direct children.',
        ],
        'pagination_selector' => [
            'label' => 'Pagination Selector',
            'description' => 'Selector for the existing semantic pagination associated with this grid.',
        ],
        'next_selector' => [
            'label' => 'Next Link Selector',
            'description' => 'Selector evaluated inside the pagination container to find the next-page link.',
        ],
        'initial_url' => [
            'label' => 'Initial Next-page URL',
            'description' => 'Optional. Leave empty to discover the URL from the existing pagination.',
        ],
        'default_text' => ['label' => 'Default Text'],
        'loading_text' => ['label' => 'Loading Text'],
        'no_more_text' => ['label' => 'No More Posts Text'],
        'button_style' => [
            'label' => 'Button Style',
            'type' => 'select',
            'options' => [
                'Default' => 'uk-button-default',
                'Primary' => 'uk-button-primary',
                'Secondary' => 'uk-button-secondary',
                'Text' => 'uk-button-text',
            ],
        ],
        'button_size' => [
            'label' => 'Button Size',
            'type' => 'select',
            'options' => [
                'Default' => '',
                'Small' => 'uk-button-small',
                'Large' => 'uk-button-large',
            ],
        ],
        'root_margin' => [
            'label' => 'Observer Root Margin',
            'description' => 'How early infinite loading begins, for example 300px 0px.',
        ],
        'debounce' => [
            'label' => 'Debounce (ms)',
            'type' => 'number',
            'attrs' => ['min' => 0, 'max' => 2000, 'step' => 50],
        ],
        'hide_pagination' => [
            'type' => 'checkbox',
            'text' => 'Hide semantic pagination after JavaScript initializes',
        ],
        'update_browser_url' => [
            'type' => 'checkbox',
            'text' => 'Update browser URL after each successful load',
        ],
        'position' => '${builder.position}',
        'position_left' => '${builder.position_left}',
        'position_right' => '${builder.position_right}',
        'position_top' => '${builder.position_top}',
        'position_bottom' => '${builder.position_bottom}',
        'position_z_index' => '${builder.position_z_index}',
        'margin_top' => '${builder.margin_top}',
        'margin_bottom' => '${builder.margin_bottom}',
        'maxwidth' => '${builder.maxwidth}',
        'maxwidth_breakpoint' => '${builder.maxwidth_breakpoint}',
        'block_align' => '${builder.block_align}',
        'block_align_breakpoint' => '${builder.block_align_breakpoint}',
        'block_align_fallback' => '${builder.block_align_fallback}',
        'text_align' => '${builder.text_align_justify}',
        'text_align_breakpoint' => '${builder.text_align_breakpoint}',
        'text_align_fallback' => '${builder.text_align_justify_fallback}',
        'animation' => '${builder.animation}',
        'visibility' => '${builder.visibility}',
        'name' => '${builder.name}',
        'status' => '${builder.status}',
        'id' => '${builder.id}',
        'class' => '${builder.cls}',
        'attributes' => '${builder.attrs}',
        'css' => [
            'label' => 'CSS',
            'type' => 'editor',
            'editor' => 'code',
            'mode' => 'css',
            'attrs' => ['debounce' => 500],
        ],
    ],
    'fieldset' => [
        'default' => [
            'type' => 'tabs',
            'fields' => [
                [
                    'title' => 'Content',
                    'fields' => [
                        'mode',
                        'target_selector',
                        'item_selector',
                        'pagination_selector',
                        'next_selector',
                        'initial_url',
                        'default_text',
                        'loading_text',
                        'no_more_text',
                    ],
                ],
                [
                    'title' => 'Settings',
                    'fields' => [
                        [
                            'label' => 'Button',
                            'type' => 'group',
                            'divider' => true,
                            'fields' => ['button_style', 'button_size'],
                        ],
                        [
                            'label' => 'Loading',
                            'type' => 'group',
                            'divider' => true,
                            'fields' => ['root_margin', 'debounce', 'hide_pagination', 'update_browser_url'],
                        ],
                        [
                            'label' => 'General',
                            'type' => 'group',
                            'fields' => [
                                'position', 'position_left', 'position_right', 'position_top', 'position_bottom',
                                'position_z_index', 'margin_top', 'margin_bottom', 'maxwidth', 'maxwidth_breakpoint',
                                'block_align', 'block_align_breakpoint', 'block_align_fallback', 'text_align',
                                'text_align_breakpoint', 'text_align_fallback', 'animation', 'visibility',
                            ],
                        ],
                    ],
                ],
                '${builder.advanced}',
            ],
        ],
    ],
];
